version: '3'
services:
  kasa-camera-frontdrive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasa-camera-frontdrive
    hostname: kasa-camera-frontdrive  # This is key for the hostname matching
    restart: unless-stopped
    ports:
      - 43330:80
    volumes:
      - ./data/master.json:/data/master.json:ro

  kasa-camera-backyard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasa-camera-backyard
    hostname: kasa-camera-backyard  # This is key for the hostname matching
    restart: unless-stopped
    ports:
      - 43331:80
    volumes:
      - ./data/master.json:/data/master.json:ro